### PR TITLE
Enable ImportControlCheck

### PR DESCRIPTION
**Pull request by tsjensen**
Here's a pull request to enable Checkstyle's [ImportControl](http://checkstyle.sourceforge.net/config_imports.html#ImportControl) check in the SonarQube plugin. Hope this helps!

### CODE REVIEW

**Comment by benzonico** [comment]
Thanks for your contribution. This will be reviewed during next checkstyle sprint.

**Comment by tsjensen** [comment]
Any feedback on this? Should I merge again with the recent updates?

**Comment by m-g-sonar** [comment]
Hello Thomas,
Thank you for work! If you merge your PR with last updates, I should be able to add it to next release of the Checkstyle plugin (2.3)

**Comment by tsjensen** [comment]
merged

**Comment by m-g-sonar** [comment]
Thanks Thomas!

I merged your PR with master, and I consequently close this PR.
To keep visibility on it, and make your contribution clearer in the release note, I created the following JIRA ticket: http://jira.codehaus.org/browse/SONARCHKST-26

Thank you again for your work!

**Pull request closed without merging**
